In [1]:
from sklearn import datasets

In [2]:
iris = datasets.load_iris()
type(iris)

sklearn.utils.Bunch

In [3]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [4]:
x = iris.data
y = iris.target
x.shape, y.shape, type(x), type(y)

((150, 4), (150,), numpy.ndarray, numpy.ndarray)

In [5]:
import numpy as np
np.unique(y)

array([0, 1, 2])

In [6]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y)
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((112, 4), (38, 4), (112,), (38,))

In [7]:
from sklearn.linear_model import LogisticRegression
log = LogisticRegression()

In [8]:
log.fit(x_train, y_train)

c:\python\python36\lib\site-packages\sklearn\linear_model\_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression()

In [9]:
log.coef_, log.intercept_

(array([[-0.37331636,  0.89408046, -2.35858268, -1.00681807],
        [ 0.40814297, -0.21469912, -0.17712954, -0.80271774],
        [-0.03482661, -0.67938135,  2.53571222,  1.80953581]]),
 array([  9.02250516,   2.27045334, -11.2929585 ]))

In [10]:
log.predict_proba(x_train[100:104])

array([[2.42708003e-05, 5.29403266e-02, 9.47035403e-01],
       [7.29876506e-02, 9.13708524e-01, 1.33038255e-02],
       [2.11698278e-02, 9.30319556e-01, 4.85106161e-02],
       [2.25681807e-01, 7.72349875e-01, 1.96831840e-03]])

In [11]:
log.predict(x_train[100:104])

array([2, 1, 1, 1])

In [12]:
1.87165482e-04 + 1.40025749e-01 + 8.59787085e-01

0.999999999482

In [13]:
from sklearn import metrics

In [15]:
y_pred = log.predict(x_train)
y_pred.shape

(112,)

In [16]:
y_pred

array([0, 2, 2, 1, 2, 1, 0, 1, 1, 2, 2, 0, 1, 1, 0, 2, 1, 0, 1, 0, 1, 0,
       0, 1, 2, 2, 1, 1, 2, 2, 0, 2, 0, 0, 0, 2, 2, 1, 2, 0, 2, 2, 0, 2,
       2, 0, 2, 2, 1, 2, 1, 1, 0, 2, 1, 0, 0, 1, 0, 0, 2, 2, 0, 0, 2, 2,
       0, 2, 2, 1, 1, 1, 1, 1, 0, 0, 0, 0, 2, 0, 0, 2, 1, 1, 2, 0, 1, 1,
       2, 2, 2, 2, 1, 1, 2, 1, 1, 1, 0, 1, 2, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 2])

In [17]:
y_train

array([0, 2, 2, 1, 2, 1, 0, 1, 1, 2, 2, 0, 1, 1, 0, 2, 1, 0, 1, 0, 1, 0,
       0, 1, 2, 2, 1, 1, 2, 2, 0, 2, 0, 0, 0, 2, 2, 1, 2, 0, 2, 1, 0, 2,
       2, 0, 2, 2, 1, 2, 1, 1, 0, 2, 1, 0, 0, 1, 0, 0, 2, 2, 0, 0, 2, 2,
       0, 1, 2, 1, 1, 1, 1, 2, 0, 0, 0, 0, 2, 0, 0, 2, 1, 1, 2, 0, 1, 1,
       2, 2, 2, 2, 1, 1, 2, 1, 1, 1, 0, 1, 2, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 2])

In [20]:
print(metrics.classification_report(y_train, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        34
           1       0.97      0.95      0.96        41
           2       0.95      0.97      0.96        37

    accuracy                           0.97       112
   macro avg       0.97      0.97      0.97       112
weighted avg       0.97      0.97      0.97       112



In [21]:
metrics.confusion_matrix(y_train, y_pred)

array([[34,  0,  0],
       [ 0, 39,  2],
       [ 0,  1, 36]], dtype=int64)